### ISSUE TITLE
Broken on OS X 10.6.7/Ruby 1.9.2

### ISSUE THREAD

**Issue by jaylevitt** [seattlerb/rdoc_osx_dictionary#1]
I think there's some bit rot.  Running rdoc_osx_dictionary now gives the error below, and there are many installed gems that are missing from Dictionary when it's done generating...

```
/Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36: warning: loading in progress, circular require considered harmful - /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/markup.rb
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/bin/rdoc_osx_dictionary:19:in `<main>'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/bin/rdoc_osx_dictionary:19:in `load'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc_osx_dictionary-1.3.1/bin/rdoc_osx_dictionary:8:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc_osx_dictionary-1.3.1/lib/rdoc_osx_dictionary.rb:4:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/ri/driver.rb:12:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/ri/formatter.rb:2:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/markup.rb:376:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/markup/fragments.rb:1:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36: warning: loading in progress, circular require considered harmful - /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/markup.rb
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/bin/rdoc_osx_dictionary:19:in `<main>'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/bin/rdoc_osx_dictionary:19:in `load'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc_osx_dictionary-1.3.1/bin/rdoc_osx_dictionary:8:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc_osx_dictionary-1.3.1/lib/rdoc_osx_dictionary.rb:4:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/ri/driver.rb:12:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/ri/formatter.rb:2:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/markup.rb:377:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/markup/inline.rb:1:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36: warning: loading in progress, circular require considered harmful - /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/markup/inline.rb
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/bin/rdoc_osx_dictionary:19:in `<main>'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/bin/rdoc_osx_dictionary:19:in `load'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc_osx_dictionary-1.3.1/bin/rdoc_osx_dictionary:8:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc_osx_dictionary-1.3.1/lib/rdoc_osx_dictionary.rb:4:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/ri/driver.rb:12:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/ri/formatter.rb:2:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/markup.rb:377:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/markup/inline.rb:126:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/gems/ruby-1.9.2-p180/gems/rdoc-2.4.3/lib/rdoc/markup/attribute_manager.rb:1:in `<top (required)>'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/jay/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
Updating ri class cache with 1986 classes...
[...]
```

**Comment by zenspider** [comment]
There is some major bitrot as rdoc was almost immediately incompatible with itself at the time I released this. I'm revamping the whole thing top to bottom to deal with rdoc ~> 3.11, so I'm already well past this issue. I should have a release out in the next week or so.
