### ISSUE TITLE
circular require considered harmful

### ISSUE THREAD

**Issue by jaylevitt** [seattlerb/rdoc_osx_dictionary#4]
This warning still occurs on OS X 10.6.8 64-bit, ruby 1.9.2-p290 rubygems 1.8.12.  It continues to run (though I have other problems I'll put in a separate bug..)

```
src% rdoc_osx_dictionary
New entries for dictionary. Rebuilding dictionary.
Sing along, kids!
<A/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36: warning: loading in progress, circular require considered harmful - /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/date/format.rb
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/bin/rdoc_osx_dictionary:19:in `<main>'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/bin/rdoc_osx_dictionary:19:in `load'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/bin/rdoc_osx_dictionary:7:in `<top (required)>'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:249:in `make'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:249:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:265:in `block in make'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:73:in `write_class_info'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:73:in `open'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:88:in `block in write_class_info'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:88:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:95:in `block (2 levels) in write_class_info'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/formatter.rb:62:in `convert'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup.rb:770:in `convert'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/document.rb:58:in `accept'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/document.rb:58:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/document.rb:61:in `block in accept'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/formatter.rb:37:in `accept_document'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/formatter.rb:37:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/formatter.rb:38:in `block in accept_document'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/verbatim.rb:21:in `accept'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/to_html.rb:195:in `accept_verbatim'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/rdoc.rb:5:in `<top (required)>'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/time.rb:39:in `<top (required)>'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/date/format.rb:4:in `<top (required)>'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/date.rb:7:in `<top (required)>'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/sdoc-0.3.16/lib/sdoc/templatable.rb:21: warning: mismatched indentations at 'end' with 'begin' at 13
/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36: warning: loading in progress, circular require considered harmful - /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/sdoc-0.3.16/lib/sdoc.rb
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/bin/rdoc_osx_dictionary:19:in `<main>'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/bin/rdoc_osx_dictionary:19:in `load'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/bin/rdoc_osx_dictionary:7:in `<top (required)>'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:249:in `make'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:249:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:265:in `block in make'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:73:in `write_class_info'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:73:in `open'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:88:in `block in write_class_info'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:88:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:95:in `block (2 levels) in write_class_info'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/formatter.rb:62:in `convert'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup.rb:770:in `convert'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/document.rb:58:in `accept'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/document.rb:58:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/document.rb:61:in `block in accept'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/formatter.rb:37:in `accept_document'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/formatter.rb:37:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/formatter.rb:38:in `block in accept_document'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/verbatim.rb:21:in `accept'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/to_html.rb:195:in `accept_verbatim'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/rdoc.rb:517:in `<top (required)>'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/rdoc.rb:517:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/rdoc.rb:519:in `block in <top (required)>'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/rdoc.rb:519:in `load'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/sdoc-0.3.16/lib/rdoc/discover.rb:3:in `<top (required)>'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/sdoc-0.3.16/lib/sdoc.rb:7:in `<top (required)>'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/sdoc-0.3.16/lib/sdoc/generator.rb:13:in `<top (required)>'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/sdoc-0.3.16/lib/sdoc/templatable.rb:2:in `<top (required)>'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
BCDEFGHIJKLMNOPQRSTUVWYZ! YAY!! All done!!!
```

**Comment by zenspider** [comment]
I think this is all from bugs in sdoc, which is being loaded by rdoc (as a plugin). Can you uninstall sdoc and test against that?

If it is a bug in sdoc, then we're gonna have to push this upstream. It probably has a really simple repro tho.

**Comment by jaylevitt** [comment]
Nope, still happens without sdoc (slightly different backtrace, of course):

```
New entries for dictionary. Rebuilding dictionary.
Sing along, kids!
A/Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36: warning: loading in progress, circular require considered harmful - /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/date/format.rb
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/bin/rdoc_osx_dictionary:19:in `<main>'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/bin/rdoc_osx_dictionary:19:in `load'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/bin/rdoc_osx_dictionary:7:in `<top (required)>'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:249:in `make'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:249:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:265:in `block in make'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:73:in `write_class_info'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:73:in `open'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:88:in `block in write_class_info'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:88:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc_osx_dictionary-2.0.0/lib/rdoc_osx_dictionary.rb:95:in `block (2 levels) in write_class_info'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/formatter.rb:62:in `convert'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup.rb:770:in `convert'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/document.rb:58:in `accept'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/document.rb:58:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/document.rb:61:in `block in accept'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/formatter.rb:37:in `accept_document'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/formatter.rb:37:in `each'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/formatter.rb:38:in `block in accept_document'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/verbatim.rb:21:in `accept'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/markup/to_html.rb:195:in `accept_verbatim'
  from /Users/jay/.rvm/gems/ruby-1.9.2-p290/gems/rdoc-3.12/lib/rdoc/rdoc.rb:5:in `<top (required)>'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/time.rb:39:in `<top (required)>'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/date/format.rb:4:in `<top (required)>'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/date.rb:7:in `<top (required)>'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
  from /Users/jay/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
BCDEFGHIJKLMNOPRSTUYZ! YAY!! All done!!!
```

**Comment by zenspider** [comment]
I still can't repro. I've got rubygems 1.8.13 and am not using rvm or anything else magical, just a plain build of ruby 1.9

```
GEM_PATH=tmp/isolate/ruby-1.9.1 ~/.multiruby/install/1.9.2-p136/bin/ruby -w -Ilib bin/rdoc_osx_dictionary  -v -f
```

You shouldn't have date.rb or date/format.rb in site_ruby. This make me suspect you have odd patches going on.

**Comment by zenspider** [comment]
I definitely think the problem is in site_ruby. You shouldn't have stdlib files (at least in name) in there. 

Please reopen if you can show that's not the problem.

**Comment by jaylevitt** [comment]
Ah HA! Blame @jeremyevans:

https://github.com/jeremyevans/home_run/blob/master/bin/home_run#L57

:)  And, yes, this doesn't happen on 1.9.3, where I didn't have that installed.  So FYI jeremy if this is a problem that home_run needs to fix.
